export const GET_PRODUCTS = 'GET_PRODUCTS';
export const FILTER_ITEMS_BY_CATEGORY = 'FILTER_ITEMS_BY_CATEGORY';
export const FILTER_ITEMS_BY_PRICE_RANGE = 'FILTER_ITEMS_BY_PRICE_RANGE';
export const FILTER_ITEMS_BY_RATING = 'FILTER_ITEMS_BY_RATING';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';